<?php

use Illuminate\Database\Seeder;
use App\Dayra;
class Dayra_Table_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //::::::::::01:::::count: 9 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'أدرار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'أولف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'أوقروت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'شروين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'فنوغيل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'رقان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'تنيركوك',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'تسابيت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>1,
            'ar_name'=>'زاوية كنتة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::02:::::count: 13 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'الشلف',
            'en_name'=>'Chlef',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'أبو الحسن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'الكريمية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'بني حواء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'أولاد فارس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'المرسى',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'تاوقريت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'وادي الفضة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);        
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'تنس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'أولاد بن عبد القادر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'عين مران',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'بوقادير',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>2,
            'ar_name'=>'الزبوجة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::03:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'أفلو',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'عين ماضي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'بريدة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'الغيشة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'قلعة سيدي سعد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'حاسي الرمل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'قصر الحيران',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'الأغواط',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'واد مرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>3,
            'ar_name'=>'سيدي مخلوف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::04:::::count: 12 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'سوق نعمان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'أم البواقي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'سيقوس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'الضلعة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'عين البيضاء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'عين بابوش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'عين فكرون',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'عين كرشة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'عين مليلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'فكرينة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>4,
            'ar_name'=>'قصر صباحي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::05:::::count: 21 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'آريس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'أولاد سلام',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'أولاد سي سليمان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'إشمول',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'الجزار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'الشمرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'المعذر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'باتنة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'بريكة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'بوزينة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'تازولت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'تكوت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'تيمقاد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'ثنية العابد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'رأس العيون',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'سريانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'سقانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'عين التوتة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'عين جاسر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'مروانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'منعة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>5,
            'ar_name'=>'نقاوس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        // $Dayra=Dayra::create([
        //     'wilaya_id'=>5,
        //     'ar_name'=>'رأس العيون',
        //     'en_name'=>'',
        //     'zip_code'=>'',
        // ]);
        //::::::::::06:::::count: 19 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'آدكار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'أقبو',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'أميزور',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'أوقاس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'برباشة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'بجاية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'بني معوش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'شميني',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'درقينة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'القصر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'إغيل علي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'خراطة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'أوزلاقن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'صدوق',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'سيدي عيش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'سوق الاثنين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'تازمالت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'تيشي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>6,
            'ar_name'=>'تيمزريت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::07:::::count: 11 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'بسكرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'جمورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'فوغالة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'القنطرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'لوطاية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'مشونش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'أورلال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'سيدي خالد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'سيدي عقبة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'طولقة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>7,
            'ar_name'=>'زريبة الوادي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::08:::::count: 12 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>8,
            'ar_name'=>'بشار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>8,
            'ar_name'=>'بني ونيف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>8,
            'ar_name'=>'تاغيت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>8,
            'ar_name'=>'ولاد خضير',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>8,
            'ar_name'=>'كرزاز',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>8,
            'ar_name'=>'العبادلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>8,
            'ar_name'=>'القنادسة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>8,
            'ar_name'=>'لحمر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::09:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'الأربعاء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'أولاد يعيش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'البليدة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'بوينان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'بوفاريك',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'بوقرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'العفرون',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'مفتاح',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'موزاية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>9,
            'ar_name'=>'وادي العلايق',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::10:::::count: 12 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'عين بسام',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'بشلول',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'بئر غبالو',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'برج أوخريص',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'البويرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'الهاشمية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'حيزر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'قادرية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'الأخضرية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'مشدا الله',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'سوق الخميس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>10,
            'ar_name'=>'سور الغزلان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::11:::::count: 7 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>11,
            'ar_name'=>'أبلسة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>11,
            'ar_name'=>'إن غار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>11,
            'ar_name'=>'تاظروك',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>11,
            'ar_name'=>'تمنراست',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>11,
            'ar_name'=>'تين زاوتين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>11,
            'ar_name'=>'عين قزام',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::12:::::count: 13 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'أم علي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'بئر العاتر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'بئر مقدم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'تبسة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'تيارت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'الشريعة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'العقلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'العوينات',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'الكويف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'الماء الأبيض',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'مرسط',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'نقرين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>12,
            'ar_name'=>'الونزة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::13:::::count: 20 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'تلمسان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'المنصورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'شتوان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'أولاد ميمون',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'عين تالوت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'بن سكران',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'الرمشي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'الحناية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'الغزوات',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'ندرومة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'فلاوسن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'مغنية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'بني بوسعيد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'صبرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'سبدو',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'سيدي الجيلالي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'بني سنوس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'باب العسة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'مرسى بن مهيدي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>13,
            'ar_name'=>'هنين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::14:::::count: 14 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'الرحوية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'السوقر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'تيارت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'حمادية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'دحموني',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'عين الذهب',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'عين كرمس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'فرندة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'قصر الشلالة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'مدروسة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'مشرع الصفاء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'مغيلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'مهدية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>14,
            'ar_name'=>'وادي ليلي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::15:::::count: 21 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'تيزي وزو',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'واسيف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'عين الحمام',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'عزازقة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'بوغني',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'ذراع الميزان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'واقنون',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'الأربعاء نايث إيراثن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'ماكودة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'أزفون',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'ذراع بن خدة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'تقزيرت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'بوزغن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'بني دوالة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'واضية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'المعاتقة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'مقلع',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'بني يني',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'تيزي راشد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'إيفرحونن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>15,
            'ar_name'=>'تيزي غنيف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::16:::::count: 14 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'الحراش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'الدار البيضاء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'درارية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'الرويبة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'الشراقة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'بئر توتة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'بئر مراد رايس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'باب الوادي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'براقي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'بوزريعة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'حسين داي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'زرالدة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'سيدي امحمد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>16,
            'ar_name'=>'الجزائر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::17:::::count: 16 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'أولاد دراج',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'أولاد سيدي إبراهيم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'الإدريسية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'البيرين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'الجلفة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'الشارف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'حاسي بحبح',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'حد الصحاري',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'دار الشيوخ',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'سيدي عيسى',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'سيدي لعجال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'عين الإبل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'عين وسارة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'فيض البطمة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'مجدل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>17,
            'ar_name'=>'مسعد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::18:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'جيجل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'السطارة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'الشقفة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'الطاهير',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'العنصر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'العوانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'الميلية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'تاكسنة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'جيملة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'زيامة منصورية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>18,
            'ar_name'=>'سيدي معروف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::19:::::count: 21 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'بني عزيز',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'العلمة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'بئر العرش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'بابور',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'بني ورتيلان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'بوعنداس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'بوقاعة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'جميلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'حمام السخنة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'حمام قرقور',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'سطيف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'صالح باي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'عموشة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'عين آزال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'عين أرنات',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'عين الكبيرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'عين ولمان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'قجال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'ماوكلان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>19,
            'ar_name'=>'قنزات',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::20:::::count: 6 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>20,
            'ar_name'=>' أولاد براهيم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>20,
            'ar_name'=>'الحساسنة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>20,
            'ar_name'=>'سيدي بوبكر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>20,
            'ar_name'=>'عين الحجر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>20,
            'ar_name'=>'يوب',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>20,
            'ar_name'=>'سعيدة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::21:::::count: 14 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'أم الطوب',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'الحدائق',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'الحروش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'القل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'بن عزوز',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'تمالوس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'رمضان جمال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'زيتونة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'سكيكدة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'سيدي مزغيش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'عزابة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'عين قشرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>21,
            'ar_name'=>'أولاد عطية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::22:::::count: 15 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'بن باديس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'تسالة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'تلاغ',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'تنيرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'رأس الماء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'سفيزف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'سيدي بلعباس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'سيدي علي بن يوب',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'سيدي علي بوسيدي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'سيدي لحسن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'عين البرد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'مرحوم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'مرين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'مولاي سليسن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>22,
            'ar_name'=>'مصطفى بن إبراهيم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::23:::::count: 7 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>23,
            'ar_name'=>'البوني',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>23,
            'ar_name'=>'الحجار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>23,
            'ar_name'=>'برحال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>23,
            'ar_name'=>'شطايبي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>23,
            'ar_name'=>'عنابة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>23,
            'ar_name'=>'الباردة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>23,
            'ar_name'=>'عين الباردة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::24:::::count: 9 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'بوشقوف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'حمام النبايل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'حمام دباغ',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'عين مخلوف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'قلعة بوصبع',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'لخزارة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'هيليوبوليس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'وادي الزناتي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>24,
            'ar_name'=>'قالمة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::25:::::count: 6 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>25,
            'ar_name'=>'قسنطينة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>25,
            'ar_name'=>'الخروب',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>25,
            'ar_name'=>'عين عبيد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>25,
            'ar_name'=>'زيغود يوسف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>25,
            'ar_name'=>'حامة بوزيان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>25,
            'ar_name'=>'ابن زياد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::26:::::count: 19 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'المدية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'وزرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'البرواقية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'عوامري',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'سغوان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'سي المحجوب',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'العمارية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'سيدي نعمان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'قصر البخاري',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'أولاد عنتر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'عزيز:',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'الشهبونية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'السواقي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'القلب الكبير',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'بني سليمان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'تابلاط',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'العزيزية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'شلالة العذاورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>26,
            'ar_name'=>'عين بوسيف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::27:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'بوقيراط',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'حاسي مماش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'خير الدين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'مستغانم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'سيدي علي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'سيدي لخضر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'عشعاشة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'عين نويسي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'عين تادلس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>27,
            'ar_name'=>'ماسرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::28:::::count: 15 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'المسيلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'حمام الضلعة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'أولاد دراج',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'سيدي عيسى',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'عين الملح',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'بن سرور',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'بوسعادة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'أولاد سيدي إبراهيم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'سيدي عامر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'مقرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'شلال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'خبانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'مجدل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'عين الحجل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>28,
            'ar_name'=>'جبل مساعد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::29:::::count: 17 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'تيزي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'البرج',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'المحمدية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'الحشم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'بوحنيفية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'تيغنيف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'زهانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'سيق',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'عقاز',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'عوف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'غريس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'معسكر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'وادي الأبطال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'وادي تاغية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'البرج',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'عين فارس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>29,
            'ar_name'=>'عين فكان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::30:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'البرمة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'النقوسة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'الحجيرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'الطيبات',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'تقرت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'تماسين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'حاسي مسعود',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'سيدي خويلد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'مقارين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>30,
            'ar_name'=>'ورقلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::31:::::count: 9 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'أرزيو',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'بئر الجير',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'بطيوة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'بوتليليس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'السانية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'عين الترك',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'قديل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'وادي تليلات',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>31,
            'ar_name'=>'وهران',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::32:::::count: 8 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>32,
            'ar_name'=>'الأبيض سيدي الشيخ',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>32,
            'ar_name'=>'بريزينة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>32,
            'ar_name'=>'بوسمغون',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>32,
            'ar_name'=>'بوعلام',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>32,
            'ar_name'=>'بوقطب',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>32,
            'ar_name'=>'البيض',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>32,
            'ar_name'=>'الرقاصة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>32,
            'ar_name'=>'الشلالة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::33:::::count: 3 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>33,
            'ar_name'=>'إليزي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>33,
            'ar_name'=>'جانت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>33,
            'ar_name'=>'إن أميناس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::34:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'برج بوعريريج',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'رأس الوادي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'برج زمورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'المنصورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'مجانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'الحمادية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'عين تاغروت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'بئر قاصد علي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'الجعافرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>34,
            'ar_name'=>'برج الغدير',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::35:::::count: 9 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'بومرداس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'برج منايل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'بودواو',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'دلس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'الثنية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'يسر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'خميس الخشنة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'الناصرية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>35,
            'ar_name'=>'بغلية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::36:::::count: 7 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>36,
            'ar_name'=>'البسباس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>36,
            'ar_name'=>'بن مهيدي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>36,
            'ar_name'=>'بوثلجة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>36,
            'ar_name'=>'بوحجار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>36,
            'ar_name'=>'الذرعان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>36,
            'ar_name'=>'الطارف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>36,
            'ar_name'=>'القالة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::37:::::count: 1 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>37,
            'ar_name'=>'تندوف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::38:::::count: 8 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>38,
            'ar_name'=>'الأزهرية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>38,
            'ar_name'=>'برج الأمير عبد القادر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>38,
            'ar_name'=>'برج بونعامة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>38,
            'ar_name'=>'تيسمسيلت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>38,
            'ar_name'=>'ثنية الأحد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>38,
            'ar_name'=>'خميستي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>38,
            'ar_name'=>'عماري',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>38,
            'ar_name'=>'لرجام',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::39:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'اميه وانسة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'البياضة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'الدبيلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'الرباح',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'الرقيبة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'المقرن',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'الوادي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'حاسي خليفة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'طالب العربي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>39,
            'ar_name'=>'قمار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::40:::::count: 8 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>40,
            'ar_name'=>'أولاد رشاش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>40,
            'ar_name'=>'الحامة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>40,
            'ar_name'=>'بابار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>40,
            'ar_name'=>'بوحمامة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>40,
            'ar_name'=>'خنشلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>40,
            'ar_name'=>'عين الطويلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>40,
            'ar_name'=>'قايس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>40,
            'ar_name'=>'ششار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::41:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'أم العظائم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'أولاد إدريس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'بئر بوحوش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'تاورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'الحدادة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'سدراتة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'سوق أهراس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'مداوروش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'المراهنة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>41,
            'ar_name'=>'المشروحة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::42:::::count: 10 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'الداموس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'القليعة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'بو إسماعيل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'تيبازة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'حجوط',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'حمر العين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'سيدي اعمر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'شرشال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'فوكة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>42,
            'ar_name'=>'قوراية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::43:::::count: 13 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'التلاغمة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'القرارم قوقة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'الرواشد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'بوحاتم',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'تاجنانت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'ترعي باينان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'تسدان حدادة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'سيدي مروان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'فرجيوة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'وادي النجاء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'شلغوم العيد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'عين البيضاء حريش',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>43,
            'ar_name'=>'ميلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::44:::::count: 14 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'الروينة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'العامرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'العبادية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'العطاف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'برج الأمير خالد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'بطحية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'بومدفع',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'جليدة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'جندل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'حمام ريغة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'خميس مليانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'عين الدفلى',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'عين لشياخ',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>44,
            'ar_name'=>'مليانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::45:::::count: 7 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>45,
            'ar_name'=>'المشرية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>45,
            'ar_name'=>'النعامة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>45,
            'ar_name'=>'صفيصيفة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>45,
            'ar_name'=>'عسلة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>45,
            'ar_name'=>'عين الصفراء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>45,
            'ar_name'=>'مغرار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>45,
            'ar_name'=>'مكمن بن عمار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::46:::::count: 8 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>46,
            'ar_name'=>'العامرية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>46,
            'ar_name'=>'المالح',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>46,
            'ar_name'=>'بني صاف',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>46,
            'ar_name'=>'حمام بوحجر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>46,
            'ar_name'=>'عين الاربعاء',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>46,
            'ar_name'=>'عين الكيحل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>46,
            'ar_name'=>'عين تموشنت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>46,
            'ar_name'=>'ولهاصة الغرابة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::47:::::count: 8 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>47,
            'ar_name'=>'بريان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>47,
            'ar_name'=>'بونورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>47,
            'ar_name'=>'زلفانة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>47,
            'ar_name'=>'ضاية بن ضحوة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>47,
            'ar_name'=>'غرداية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>47,
            'ar_name'=>'القرارة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>47,
            'ar_name'=>'متليلي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>47,
            'ar_name'=>'المنصورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::48:::::count: 13 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'الحمادنة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'الرمكة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'المطمر',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'جديوية',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'زمورة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'سيدي امحمد بن علي',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'عمي موسى',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'عين طارق',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'غليزان',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'مازونة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'منداس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'وادي ارهيو',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>48,
            'ar_name'=>'يلل',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::49:::::count: 4 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>49,
            'ar_name'=>'أوقروت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>49,
            'ar_name'=>'تيميمون',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>49,
            'ar_name'=>'تينركوك',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>49,
            'ar_name'=>'شروين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::50:::::count: 4 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>50,
            'ar_name'=>'برج باجي مختار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::51:::::count: 1 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>51,
            'ar_name'=>'سيدي خالد',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>51,
            'ar_name'=>'أولاد جلال',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::52:::::count: 1 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>52,
            'ar_name'=>'بني عباس',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::53:::::count: 2 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>53,
            'ar_name'=>'عين صالح',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>53,
            'ar_name'=>'إن غار',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::54:::::count: 2 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>54,
            'ar_name'=>'عين قزام',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>54,
            'ar_name'=>'تين زاوتين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::55:::::count: 6 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>55,
            'ar_name'=>'تقرت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>55,
            'ar_name'=>'تماسين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>55,
            'ar_name'=>'مقارين',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>55,
            'ar_name'=>'الطيبات',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>55,
            'ar_name'=>'الحجيرة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        $Dayra=Dayra::create([
            'wilaya_id'=>55,
            'ar_name'=>'البرمة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::56:::::count: 1 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>56,
            'ar_name'=>'جانت',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::57:::::count: 1 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>57,
            'ar_name'=>'المغير',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
        //::::::::::58:::::count: 1 :::
        $Dayra=Dayra::create([
            'wilaya_id'=>58,
            'ar_name'=>'المنيعة',
            'en_name'=>'',
            'zip_code'=>'',
        ]);
    }
}
