<?php

use Illuminate\Database\Seeder;
use App\Wilaya;

class Wilaya_Table_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Adrar=wilaya::create([
            'ar_name'=>'أدرار',
            'en_name'=>'Adrar',
            'zip_code'=>'01',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'شلف',
            'en_name'=>'chlef',
            'zip_code'=>'02',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'الأغواط',
            'en_name'=>'',
            'zip_code'=>'03',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'أم البواقي',
            'en_name'=>'',
            'zip_code'=>'04',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'باتنة',
            'en_name'=>'',
            'zip_code'=>'05',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'بجاية',
            'en_name'=>'',
            'zip_code'=>'06',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'بسكرة',
            'en_name'=>'',
            'zip_code'=>'07',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'بشار',
            'en_name'=>'',
            'zip_code'=>'08',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'البليدة',
            'en_name'=>'',
            'zip_code'=>'09',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'البويرة',
            'en_name'=>'',
            'zip_code'=>'10',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تمنراست',
            'en_name'=>'',
            'zip_code'=>'11',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تبسة',
            'en_name'=>'',
            'zip_code'=>'12',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تلمسان',
            'en_name'=>'',
            'zip_code'=>'13',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تيارت',
            'en_name'=>'',
            'zip_code'=>'14',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تيزي وزو',
            'en_name'=>'',
            'zip_code'=>'15',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'الجزائر',
            'en_name'=>'',
            'zip_code'=>'16',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'الجلفة',
            'en_name'=>'',
            'zip_code'=>'17',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'جيجل',
            'en_name'=>'',
            'zip_code'=>'18',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'سطيف',
            'en_name'=>'',
            'zip_code'=>'19',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'سعيدة',
            'en_name'=>'',
            'zip_code'=>'20',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'سكيكدة',
            'en_name'=>'',
            'zip_code'=>'21',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'سيدي بلعباس',
            'en_name'=>'',
            'zip_code'=>'22',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'عنابة',
            'en_name'=>'',
            'zip_code'=>'23',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'قالمة',
            'en_name'=>'',
            'zip_code'=>'24',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'قسنطينة',
            'en_name'=>'',
            'zip_code'=>'25',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'المدية',
            'en_name'=>'',
            'zip_code'=>'26',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'مستغانم',
            'en_name'=>'',
            'zip_code'=>'27',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'المسيلة',
            'en_name'=>'',
            'zip_code'=>'28',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'معسكر',
            'en_name'=>'',
            'zip_code'=>'29',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'ورقلة',
            'en_name'=>'',
            'zip_code'=>'30',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'وهران',
            'en_name'=>'',
            'zip_code'=>'31',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'البيض',
            'en_name'=>'',
            'zip_code'=>'32',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'إليزي',
            'en_name'=>'',
            'zip_code'=>'33',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'برج بوعريريج',
            'en_name'=>'',
            'zip_code'=>'34',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'بومرداس',
            'en_name'=>'',
            'zip_code'=>'35',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'الطارف',
            'en_name'=>'',
            'zip_code'=>'36',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تندوف',
            'en_name'=>'',
            'zip_code'=>'37',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تيسمسيلت',
            'en_name'=>'',
            'zip_code'=>'38',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'الوادي',
            'en_name'=>'',
            'zip_code'=>'39',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'خنشلة',
            'en_name'=>'',
            'zip_code'=>'40',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'سوق أهراس',
            'en_name'=>'',
            'zip_code'=>'41',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تيبازة',
            'en_name'=>'',
            'zip_code'=>'42',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'ميلة',
            'en_name'=>'',
            'zip_code'=>'43',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'عين الدفلى',
            'en_name'=>'',
            'zip_code'=>'44',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'النعامة',
            'en_name'=>'',
            'zip_code'=>'45',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'عين تموشنت',
            'en_name'=>'',
            'zip_code'=>'46',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'غرداية',
            'en_name'=>'',
            'zip_code'=>'47',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'غليزان',
            'en_name'=>'',
            'zip_code'=>'48',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تيميمون',
            'en_name'=>'',
            'zip_code'=>'49',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'برج باجي مختار',
            'en_name'=>'',
            'zip_code'=>'50',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'أولاد جلال',
            'en_name'=>'',
            'zip_code'=>'51',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'بني عباس',
            'en_name'=>'',
            'zip_code'=>'52',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'عين صالح',
            'en_name'=>'',
            'zip_code'=>'53',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'عين قزام',
            'en_name'=>'',
            'zip_code'=>'54',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'تقرت',
            'en_name'=>'',
            'zip_code'=>'55',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'جانت',
            'en_name'=>'',
            'zip_code'=>'56',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'المغير',
            'en_name'=>'',
            'zip_code'=>'57',
        ]);
        $Adrar=wilaya::create([
            'ar_name'=>'المنيعة',
            'en_name'=>'',
            'zip_code'=>'58',
        ]);
    }
}
