@extends('admin.layouts.app')
@section('header')
@include('admin.inc.header.index')
@endsection
@section('side-bar')
@include('admin.inc.side-bar.index')
@endsection
@section('content-wrapper')
@include('admin.inc.content-wrapper.notifications.order-to-find-reale-estate-notifications.index')
@endsection
@section('main-footer')
@include('admin.inc.main-footer.index')
@endsection
@section('control-sidebar')
@include('admin.inc.control-sidebar.index')
@endsection